export const GigsActionTypes = {
  SET_UNASSIGNED_GIGS: 'SET_UNASSIGNED_GIGS',
  SET_MY_GIGS: 'SET_MY_GIGS',
  SET_MY_POSTED_GIGS: 'SET_MY_POSTED_GIGS',
  CLEAR_MY_GIGS: 'CLEAR_MY_GIGS',
  TOGGLE_POSTED_GIGS_HIDDEN: 'TOGGLE_POSTED_GIGS_HIDDEN',
  SET_SEARCH_AVAILABLE_GIGS: 'SET_SEARCH_AVAILABLE_GIGS'
};
